"""
Agentic Platform -- MCP Linter Outreach Tool

Finds MCP server repos on GitHub, runs our manifest linter against any tool
definitions found in their READMEs, and prepares GitHub issues for repos with
real problems.

This is agent-to-agent-developer outreach: we find repos building MCP tools,
check their quality, and offer concrete help.

Usage:
    python -m outreach.lint_outreach --dry-run   # scan and save, don't post
    python -m outreach.lint_outreach --post       # actually open GitHub issues

Output goes to: outreach/results/
"""

import argparse
import base64
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Set

# Add the server root to sys.path so we can import from skills/
SCRIPT_DIR = Path(__file__).parent
SERVER_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SERVER_ROOT))

from skills.free.manifest_lint import run_manifest_lint, RULES

# --- Config ---

MAX_REPOS_PER_RUN = 5
SLEEP_BETWEEN_CALLS = 2  # seconds

RESULTS_DIR = SCRIPT_DIR / "results"

ATTRIBUTION = (
    "Generated by [Agentic Platform MCP Linter](https://github.com/andysalvo/agentic-platform) "
    "-- a free, open tool that checks MCP tool definitions for quality issues. No API key needed."
)


# --- GitHub API helpers ---

def gh_api(path: str, extra_args: Optional[List[str]] = None) -> Optional[str]:
    """Call the gh CLI and return stdout, or None on failure."""
    cmd = ["gh", "api", path]
    if extra_args:
        cmd.extend(extra_args)
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"  [gh error] {result.stderr.strip()[:200]}", file=sys.stderr)
            return None
        return result.stdout
    except subprocess.TimeoutExpired:
        print("  [gh error] timeout", file=sys.stderr)
        return None
    except FileNotFoundError:
        print("  [error] gh CLI not found. Install from https://cli.github.com", file=sys.stderr)
        sys.exit(1)


def search_mcp_repos(count: int = MAX_REPOS_PER_RUN) -> List[str]:
    """Search GitHub for repos with the mcp-server topic, sorted by recently updated."""
    print(f"Searching GitHub for MCP server repos (top {count})...")
    raw = gh_api(
        "search/repositories",
        [
            "-q", ".items[].full_name",
            "-f", "q=topic:mcp-server sort:updated",
            "-f", f"per_page={count}",
        ],
    )
    if not raw:
        return []
    repos = [line.strip() for line in raw.strip().splitlines() if line.strip()]
    print(f"  Found {len(repos)} repos.")
    return repos[:count]


def fetch_readme(full_name: str) -> Optional[str]:
    """Fetch a repo's README content (decoded from base64)."""
    owner, repo = full_name.split("/", 1)
    raw = gh_api(f"repos/{owner}/{repo}/readme", ["-q", ".content"])
    if not raw or not raw.strip():
        return None
    try:
        # GitHub returns base64 with newlines embedded; strip them before decoding
        b64 = raw.strip().replace("\n", "").replace("\\n", "")
        return base64.b64decode(b64).decode("utf-8", errors="replace")
    except Exception as e:
        print(f"  [readme decode error] {e}", file=sys.stderr)
        return None


def open_github_issue(full_name: str, title: str, body: str) -> Optional[str]:
    """Create a GitHub issue on a repo. Returns the issue URL or None."""
    owner, repo = full_name.split("/", 1)
    cmd = [
        "gh", "issue", "create",
        "--repo", full_name,
        "--title", title,
        "--body", body,
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"  [issue error] {result.stderr.strip()[:300]}", file=sys.stderr)
            return None
        return result.stdout.strip()
    except subprocess.TimeoutExpired:
        print("  [issue error] timeout", file=sys.stderr)
        return None


# --- Tool definition extraction ---

# Patterns that indicate a JSON block is likely to contain MCP tool definitions
_TOOL_SIGNALS = re.compile(
    r'"name"\s*:\s*"[^"]{2,40}".*?"description"\s*:\s*"',
    re.DOTALL,
)

def extract_json_blocks(text: str) -> List[str]:
    """
    Find all ```json ... ``` blocks in a README and return the raw JSON strings.
    Also looks for bare JSON arrays that look like tool definition lists.
    """
    blocks = []

    # Fenced code blocks: ```json ... ``` or ``` ... ```
    fenced = re.findall(r"```(?:json)?\s*(\[[\s\S]*?\]|\{[\s\S]*?\})\s*```", text)
    blocks.extend(fenced)

    # Inline JSON arrays that aren't in fenced blocks
    # Look for top-level arrays starting with [{ that span multiple lines
    standalone = re.findall(r"(?<![`\w])(\[\s*\{[\s\S]{50,2000}?\}\s*\])(?![`\w])", text)
    blocks.extend(standalone)

    return blocks


def find_tool_definitions(readme: str) -> List[dict]:
    """
    Parse JSON blocks from a README and return any that look like MCP tool definitions.
    Returns a flat list of tool dicts (may come from multiple blocks).
    """
    found_tools = []
    seen_names = set()

    for block in extract_json_blocks(readme):
        # Quick signal check before full parse
        if not _TOOL_SIGNALS.search(block):
            continue
        try:
            data = json.loads(block)
        except json.JSONDecodeError:
            continue

        # Normalize: could be a single tool dict or a list of them
        if isinstance(data, dict) and "name" in data:
            candidates = [data]
        elif isinstance(data, list):
            candidates = [item for item in data if isinstance(item, dict) and "name" in item]
        else:
            continue

        # Filter to items that look like MCP tools (have name + description or inputSchema)
        for item in candidates:
            if "name" not in item:
                continue
            if not ("description" in item or "inputSchema" in item or "parameters" in item):
                continue
            name = item.get("name", "")
            if name not in seen_names:
                seen_names.add(name)
                found_tools.append(item)

    return found_tools


# --- Lint and issue generation ---

def lint_tools(tools: list[dict]) -> dict:
    """
    Run the manifest linter and return a structured result dict.
    """
    tools_json = json.dumps(tools)
    report_text = run_manifest_lint(tools_json)

    # Count issues by severity by re-running the rules (linter returns Markdown)
    critical_count = 0
    warning_count = 0
    info_count = 0
    issues_by_tool: dict[str, list[dict]] = {}

    for tool in tools:
        tool_name = tool.get("name", "(unnamed)")
        tool_issues = []
        for rule in RULES:
            try:
                passed = rule["check"](tool)
            except Exception:
                passed = True
            if not passed:
                tool_issues.append({
                    "id": rule["id"],
                    "severity": rule["severity"],
                    "message": rule["message"],
                    "fix": rule["fix"],
                })
                if rule["severity"] == "critical":
                    critical_count += 1
                elif rule["severity"] == "warning":
                    warning_count += 1
                elif rule["severity"] == "info":
                    info_count += 1
        issues_by_tool[tool_name] = tool_issues

    return {
        "report_text": report_text,
        "critical": critical_count,
        "warnings": warning_count,
        "info": info_count,
        "issues_by_tool": issues_by_tool,
        "tools_checked": len(tools),
    }


def build_issue_body(repo: str, lint_result: dict) -> str:
    """Build a GitHub issue body from lint results."""
    tool_count = lint_result["tools_checked"]
    critical = lint_result["critical"]
    warnings = lint_result["warnings"]

    lines = [
        f"## MCP Tool Definition Quality Report",
        f"",
        f"Hi! I ran your MCP tool definitions through the "
        f"[Agentic Platform MCP Linter](https://github.com/andysalvo/agentic-platform) "
        f"and found some issues that may affect how AI agents discover and use your tools.",
        f"",
        f"**{tool_count} tool(s) checked** -- "
        f"**{critical} critical** / **{warnings} warnings**",
        f"",
        f"---",
        f"",
        f"### Lint Report",
        f"",
        lint_result["report_text"],
        f"",
        f"---",
        f"",
        f"### Why this matters",
        f"",
        f"MCP clients use tool descriptions and parameter schemas to decide which tools "
        f"to call and how to call them. Missing or low-quality descriptions lead to:",
        f"",
        f"- Agents skipping your tools in favor of better-documented alternatives",
        f"- Incorrect parameter values being passed",
        f"- Silent failures that are hard to debug",
        f"",
        f"---",
        f"",
        f"*{ATTRIBUTION}*",
        f"",
        f"Feel free to close this if it isn't useful. Happy to answer questions.",
    ]

    return "\n".join(lines)


def build_issue_title(repo: str, lint_result: dict) -> str:
    critical = lint_result["critical"]
    warnings = lint_result["warnings"]
    tool_count = lint_result["tools_checked"]

    if critical > 0:
        return f"MCP tool definitions: {critical} critical issue(s) found by automated linter"
    elif warnings > 0:
        return f"MCP tool definitions: {warnings} warning(s) found by automated linter"
    else:
        return f"MCP tool definitions: {tool_count} tool(s) scanned, minor improvements available"


# --- Results persistence ---

def save_results(run_results: list[dict], run_id: str) -> Path:
    """Save the full run results to a JSON file."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESULTS_DIR / f"run_{run_id}.json"
    with open(out_path, "w") as f:
        json.dump(run_results, f, indent=2)
    return out_path


def load_posted_repos() -> set[str]:
    """
    Load the set of repos we've already posted issues to, to avoid duplicates.
    Scans all result files in the results directory.
    """
    posted = set()
    if not RESULTS_DIR.exists():
        return posted
    for path in RESULTS_DIR.glob("run_*.json"):
        try:
            with open(path) as f:
                results = json.load(f)
            for entry in results:
                if entry.get("issue_posted"):
                    posted.add(entry["repo"])
        except (json.JSONDecodeError, KeyError):
            continue
    return posted


# --- Main loop ---

def run_outreach(post: bool = False) -> None:
    """
    Main outreach loop. Scans repos, lints tool definitions, and either saves
    issues for review (dry-run) or posts them directly (--post).
    """
    mode = "LIVE (will post issues)" if post else "DRY RUN (no issues posted)"
    run_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    print(f"=== Agentic Platform Lint Outreach ===")
    print(f"Mode: {mode}")
    print(f"Run ID: {run_id}")
    print(f"Results dir: {RESULTS_DIR}")
    print()

    already_posted = load_posted_repos()
    if already_posted:
        print(f"Skipping {len(already_posted)} repos already contacted.")
        print()

    repos = search_mcp_repos(count=MAX_REPOS_PER_RUN)
    if not repos:
        print("No repos found. Check your gh auth status.")
        return

    run_results = []

    for i, repo in enumerate(repos):
        print(f"[{i+1}/{len(repos)}] {repo}")

        entry = {
            "repo": repo,
            "run_id": run_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "readme_found": False,
            "tools_found": 0,
            "lint_result": None,
            "issue_title": None,
            "issue_body": None,
            "issue_url": None,
            "issue_posted": False,
            "skipped_reason": None,
        }

        # Skip already-contacted repos
        if repo in already_posted:
            print(f"  Skipped -- already posted an issue here.")
            entry["skipped_reason"] = "already_posted"
            run_results.append(entry)
            time.sleep(SLEEP_BETWEEN_CALLS)
            continue

        # Fetch README
        readme = fetch_readme(repo)
        if not readme:
            print(f"  No README found or fetch failed.")
            entry["skipped_reason"] = "no_readme"
            run_results.append(entry)
            time.sleep(SLEEP_BETWEEN_CALLS)
            continue

        entry["readme_found"] = True
        print(f"  README: {len(readme)} chars")

        # Extract tool definitions
        tools = find_tool_definitions(readme)
        entry["tools_found"] = len(tools)

        if not tools:
            print(f"  No MCP tool definitions found in README.")
            entry["skipped_reason"] = "no_tool_definitions"
            run_results.append(entry)
            time.sleep(SLEEP_BETWEEN_CALLS)
            continue

        print(f"  Found {len(tools)} tool definition(s): {[t.get('name') for t in tools]}")

        # Run linter
        lint_result = lint_tools(tools)
        entry["lint_result"] = {
            "critical": lint_result["critical"],
            "warnings": lint_result["warnings"],
            "info": lint_result["info"],
            "tools_checked": lint_result["tools_checked"],
        }

        actionable = lint_result["critical"] + lint_result["warnings"]
        print(f"  Lint: {lint_result['critical']} critical, {lint_result['warnings']} warnings, {lint_result['info']} info")

        if actionable == 0:
            print(f"  Clean -- no critical or warning issues. Skipping.")
            entry["skipped_reason"] = "no_actionable_issues"
            run_results.append(entry)
            time.sleep(SLEEP_BETWEEN_CALLS)
            continue

        # Build issue
        issue_title = build_issue_title(repo, lint_result)
        issue_body = build_issue_body(repo, lint_result)
        entry["issue_title"] = issue_title
        entry["issue_body"] = issue_body

        if post:
            print(f"  Posting issue: \"{issue_title}\"")
            url = open_github_issue(repo, issue_title, issue_body)
            if url:
                entry["issue_url"] = url
                entry["issue_posted"] = True
                print(f"  Issue posted: {url}")
            else:
                print(f"  Failed to post issue.")
        else:
            print(f"  [DRY RUN] Would post: \"{issue_title}\"")

        run_results.append(entry)

        # Rate limiting
        if i < len(repos) - 1:
            time.sleep(SLEEP_BETWEEN_CALLS)

    # Save results
    out_path = save_results(run_results, run_id)
    print()
    print(f"=== Run complete ===")
    print(f"Repos scanned: {len(repos)}")
    issues_prepped = sum(1 for r in run_results if r.get("issue_title"))
    issues_posted = sum(1 for r in run_results if r.get("issue_posted"))
    print(f"Issues prepared: {issues_prepped}")
    if post:
        print(f"Issues posted: {issues_posted}")
    else:
        print(f"Issues posted: 0 (dry run -- use --post to open them)")
    print(f"Results saved to: {out_path}")


# --- Entry point ---

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Scan GitHub for MCP server repos, lint their tool definitions, "
            "and prepare (or post) quality improvement issues."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python -m outreach.lint_outreach --dry-run    # default, safe\n"
            "  python -m outreach.lint_outreach --post       # actually opens issues\n"
        ),
    )

    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "--dry-run",
        action="store_true",
        default=True,
        help="Scan repos and save results without posting issues (default).",
    )
    mode_group.add_argument(
        "--post",
        action="store_true",
        default=False,
        help="Actually open GitHub issues on repos with problems.",
    )

    args = parser.parse_args()
    run_outreach(post=args.post)


if __name__ == "__main__":
    main()
